### ISSUE TITLE
Disabling smileys

### ISSUE THREAD

**Issue by Sorunome** [toxygen-project/toxygen#20]
When disabling smileys toxygen adds weird upon restart:

When sending a message it seemingly doesn't get sent, that is, the message stays in the text box below and nothing new appears in the message view.

However, the message does actually get sent and the friend sees it

**Comment by ingvar1995** [comment]
What version?

**Comment by Sorunome** [comment]
```
sorunome@sorunome-desktop ~ $ toxygen --version
Toxygen v0.2.4
```

**Comment by ingvar1995** [comment]
Can ypu post example of 'wrong' message?

**Comment by Sorunome** [comment]
Any message being sent.

```
sorunome@sorunome-desktop ~ $ toxygen
Fontconfig error: "/home/sorunome/.config/fontconfig/fonts.conf", line 1: XML or text declaration not at start of entity
Fontconfig error: "~/.fonts.conf", line 1: XML or text declaration not at start of entity

(python3:6719): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
ALSA lib pcm.c:2450:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2450:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2450:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:867:(find_matching_chmap) Found no matching channel map
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Plugin AutoAwayStatusLinux
Connection status:  2
Friend #8 connection status: 1
Friend #20 connection status: 2
New name friend #20
User #20 has new status
Friend's #20 status changed!
Friend #27 connection status: 1
Avatar
New name friend #27
User #27 has new status
Friend's #27 status changed!
Friend #27 connection status: 2
Traceback (most recent call last):
  File "/opt/toxygen/toxygen/mainscreen.py", line 640, in friend_click
    self.profile.set_active(num)
  File "/opt/toxygen/toxygen/profile.py", line 196, in set_active
    data[3])
  File "/opt/toxygen/toxygen/profile.py", line 582, in create_message_item
    item = MessageItem(text, time, name, owner != MESSAGE_OWNER['NOT_SENT'], message_type, self._messages)
  File "/opt/toxygen/toxygen/list_items.py", line 154, in __init__
    self.message = MessageEdit(text, parent.width() - 150, message_type, self)
  File "/opt/toxygen/toxygen/list_items.py", line 28, in __init__
    self.setSearchPaths([smileys.SmileyLoader.get_instance().get_smileys_path()])
  File "/opt/toxygen/toxygen/smileys.py", line 51, in get_smileys_path
    return util.curr_directory() + '/smileys/' + self._curr_pack + '/'
TypeError: Can't convert 'NoneType' object to str implicitly
New name friend #8
User #8 has new status
Friend's #8 status changed!
Traceback (most recent call last):
  File "/opt/toxygen/toxygen/mainscreen_widgets.py", line 37, in keyPressEvent
    self.parent.send_message()
  File "/opt/toxygen/toxygen/mainscreen.py", line 467, in send_message
    self.profile.send_message(text)
  File "/opt/toxygen/toxygen/profile.py", line 433, in send_message
    self.create_message_item(text, t, MESSAGE_OWNER['NOT_SENT'], message_type)
  File "/opt/toxygen/toxygen/profile.py", line 582, in create_message_item
    item = MessageItem(text, time, name, owner != MESSAGE_OWNER['NOT_SENT'], message_type, self._messages)
  File "/opt/toxygen/toxygen/list_items.py", line 154, in __init__
    self.message = MessageEdit(text, parent.width() - 150, message_type, self)
  File "/opt/toxygen/toxygen/list_items.py", line 28, in __init__
    self.setSearchPaths([smileys.SmileyLoader.get_instance().get_smileys_path()])
  File "/opt/toxygen/toxygen/smileys.py", line 51, in get_smileys_path
    return util.curr_directory() + '/smileys/' + self._curr_pack + '/'
TypeError: Can't convert 'NoneType' object to str implicitly
Exception in file sending: Can't convert 'NoneType' object to str implicitly
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/toxygen/toxygen/plugins/awayl.py", line 95, in loop
    d = check_output(['xprintidle'])
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'xprintidle'
```
Sorry for not having sent the output before, i somehow....didn't think of it

**Comment by ingvar1995** [comment]
This bug requires one line fix. Btw do you use auto away status linux plugin? It requires additional dep - package xprintidle. I don't sure it's available on Arch. If not, I can try to write special plugin for Arch later

**Comment by Sorunome** [comment]
Yes, i do use the auto-away plugin. The smiley bug was also present before using it, though. xprintidle is available in the AUR

**Comment by ingvar1995** [comment]
But plugin can't find it. Why? Can you try 'xprintidle' in your terminal?

**Comment by Sorunome** [comment]
Sorry for the confusion, i didn't know it required xprintidle until you just pointed it out so then i checked in the repos and the aur, found it in the aur, installed it and now it is running fine, the plugin
