### ISSUE TITLE
Database is locked

### ISSUE THREAD

**Issue by Sorunome** [toxygen-project/toxygen#26]
Today toxygen wouldn't start, running it in the terminal it gave "database is locked".
```
Traceback (most recent call last):
  File "/opt/toxygen/toxygen/main.py", line 462, in <module>
    main()
  File "/opt/toxygen/toxygen/main.py", line 458, in main
    toxygen.main()
  File "/opt/toxygen/toxygen/main.py", line 184, in main
    self.ms = MainWindow(self.tox, self.reset, self.tray)
  File "/opt/toxygen/toxygen/mainscreen.py", line 20, in __init__
    self.initUI(tox)
  File "/opt/toxygen/toxygen/mainscreen.py", line 326, in initUI
    self.profile = Profile(tox, self)
  File "/opt/toxygen/toxygen/profile.py", line 63, in __init__
    self._history.add_friend_to_db(tox_id)
  File "/opt/toxygen/toxygen/history.py", line 69, in add_friend_to_db
    cursor.execute('CREATE TABLE id' + tox_id + '('
sqlite3.OperationalError: database is locked
```
Perhaps have a prompt then saying there might be another instance running, if I am sure I want to start toxygen (and unlock the DB)?

Also, how do I manually unlock the DB?

**Comment by ingvar1995** [comment]
Did 97ce2b9 help?

**Comment by Sorunome** [comment]
is it already merged to master branch? I just re-built toxygen-git from the AUR and it is still present there.

**Comment by ingvar1995** [comment]
No, it is in develop branch

**Comment by ingvar1995** [comment]
Seems that db lock is finally fixed in develop branch. Not sure that it can unlock already locked db, but db locking doesn't occur
