### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by Sorunome** [toxygen-project/toxygen#38]
```
sorunome@sorunome-desktop ~ $ toxygen                                                                                         130
Traceback (most recent call last):
  File "/usr/bin/toxygen", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PyAudio' distribution was not found and is required by Toxygen
```

**Comment by ingvar1995** [comment]
Module PyAudio is missing. try to install it via ``pip3 install pyaudio`` or using package manager

**Comment by Sorunome** [comment]
Sorry for being too stupid to read output today, it's working now ^.^
