### ISSUE TITLE
Build problem.

### ISSUE THREAD

**Issue by tele1** [toxygen-project/toxygen#46]
```
$ python setup.py
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from toxygen.util import program_version
  File "/home/tele/Pobrane/Prog/toxygen-0.2.8/toxygen/util.py", line 16
    nonlocal saved_result
                        ^
SyntaxError: invalid syntax
tele@tee:~/Pobrane/Prog/toxygen-0.2.8$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from toxygen.util import program_version
  File "/home/tele/Pobrane/Prog/toxygen-0.2.8/toxygen/util.py", line 16
    nonlocal saved_result
                        ^
SyntaxError: invalid syntax
```

toxygen-0.2.8
OS: Debian 9.0

**Comment by SHooZ** [comment]
Try to use a 'python3' instead of 'python':
`python3 setup.py install`

**Comment by tele1** [comment]
Installed additionally for build:  setuptools
for run:  python3-pyaudio , python-qt4

```
python3 setup.py build
python3 setup.py install --user --record files.txt
```

```
$ python3 ~/.local/bin/toxygen
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Violation of memory protection
```

I tried create new account and "Violation of memory protection"
I have with qTox also "Violation of memory protection"
I use toxcore 0.1.9.  https://github.com/TokTok/c-toxcore/issues/567

**Comment by ingvar1995** [comment]
Use irungentoo/toxcore for toxygen and it will work ;)
