### ISSUE TITLE
AttributeError: type object 'EchoMode' has no attribute 'Password'

### ISSUE THREAD

**Issue by Fak3** [toxygen-project/toxygen#47]
I installed toxygen version 0.2.8.0 from current git master and got this error when launched and clicked "load profile"
```
u1@pc1:~> toxygen 
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "/usr/bin/toxygen", line 9, in <module>
    load_entry_point('Toxygen==0.2.8.0', 'console_scripts', 'toxygen')()
  File "/usr/lib/python3.4/site-packages/toxygen/main.py", line 513, in main
    toxygen.main()
  File "/usr/lib/python3.4/site-packages/toxygen/main.py", line 166, in main
    data = self.enter_pass(data)
  File "/usr/lib/python3.4/site-packages/toxygen/main.py", line 42, in enter_pass
    p = PasswordScreen(toxes.ToxES.get_instance(), tmp)
  File "/usr/lib/python3.4/site-packages/toxygen/passwordscreen.py", line 72, in __init__
    super(PasswordScreen, self).__init__(encrypt)
  File "/usr/lib/python3.4/site-packages/toxygen/passwordscreen.py", line 27, in __init__
    self.initUI()
  File "/usr/lib/python3.4/site-packages/toxygen/passwordscreen.py", line 37, in initUI
    self.password = PasswordArea(self)
  File "/usr/lib/python3.4/site-packages/toxygen/passwordscreen.py", line 13, in __init__
    self.setEchoMode(QtGui.QLineEdit.EchoMode.Password)
AttributeError: type object 'EchoMode' has no attribute 'Password'
```

**Comment by ingvar1995** [comment]
Are you using PySide or PyQt4?

**Comment by Fak3** [comment]
PyQt4

**Comment by ingvar1995** [comment]
I'm closing this because v0.3.0 uses PyQt5, so this issue is resolved
