### ISSUE TITLE
New version 0.4.1 crashes on start

### ISSUE THREAD

**Issue by alextech** [toxygen-project/toxygen#58]
After upgrade new version 0.4.1 on latest Fedora 27 crashes with 

```
Traceback (most recent call last):
  File "toxygen/main.py", line 2, in <module>
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "toxygen/loginscreen.py", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
ImportError: /lib64/libGL.so.1: undefined symbol: _glapi_tls_Current
[3448] Failed to execute script main
```

**Comment by ingvar1995** [comment]
Try updated release: https://github.com/toxygen-project/toxygen/releases/download/v0.4.1/toxygen_linux_64.tar.gz

**Comment by alextech** [comment]
works now. Thank you!
