### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by tr37ion** [toxygen-project/toxygen#70]
Using the ArchLinux [AUR](https://aur.archlinux.org/packages/toxygen-git/) package and starting toxygen results in.
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/toxygen/libtox.py", line 54, in __init__
    self._lib_tox_encrypt_save = CDLL('libtoxencryptsave.so')
  File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtoxencryptsave.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/toxygen", line 11, in <module>
    load_entry_point('Toxygen==0.4.1.0', 'console_scripts', 'toxygen')()
  File "/usr/lib/python3.7/site-packages/toxygen/main.py", line 483, in main
    toxygen.main()
  File "/usr/lib/python3.7/site-packages/toxygen/main.py", line 61, in main
    encrypt_save = toxes.ToxES()
  File "/usr/lib/python3.7/site-packages/toxygen/toxes.py", line 9, in __init__
    self._toxencryptsave = toxencryptsave.ToxEncryptSave()
  File "/usr/lib/python3.7/site-packages/toxygen/toxencryptsave.py", line 9, in __init__
    self.libtoxencryptsave = libtox.LibToxEncryptSave()
  File "/usr/lib/python3.7/site-packages/toxygen/libtox.py", line 56, in __init__
    self._lib_tox_encrypt_save = CDLL(util.curr_directory() + '/libs/libtoxencryptsave.so')
  File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/python3.7/site-packages/toxygen/libs/libtoxencryptsave.so: cannot open shared object file: No such file or directory
```
Any ideas how to fix this?

**Comment by ingvar1995** [comment]
Seems that aur package uses toktok-toxcore as dependency while toxygen requires vanilla toxcore. I recommend to contact package maintainer and ask him about deps

**Comment by tr37ion** [comment]
Looking at the package's [build script](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=toxygen-git) it doesn't seem to use toktok-toxcore from what I'm seeing.

**Comment by ingvar1995** [comment]
Most of clients use toktok now, so probably it's better to separate toxcore and toktok toxcore in aur (create 2 packages I mean). I'm going to migrate to toktok core too, but this won't happen until Toxygen v0.5.0 which is still far from being ready to release. So there are 3 possible solutions:

1) Create new package for old toxcore in aur and target it in toxygen (can package maintainer do it?)
2) Migrate latest (0.4.1) version to toktok (require too much work from me)
3) Wait for 0.5.0, but probably I will use custom core there. (anyway I will try to fix packages for all repos)

Looks like the 1st solution is the easiest fkr now
