### ISSUE TITLE
OSError: exception: access violation reading 0x000000007998B3C0 in win10 64bit

### ISSUE THREAD

**Issue by arnking** [toxygen-project/toxygen#74]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.5\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.3.5\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/tonad/Downloads/toxygen-master/toxygen/main.py", line 486, in <module>
    main()
  File "C:/Users/tonad/Downloads/toxygen-master/toxygen/main.py", line 482, in main
    toxygen.main()
  File "C:/Users/tonad/Downloads/toxygen-master/toxygen/main.py", line 153, in main
    self.tox = profile.tox_factory(data, settings)
  File "C:\Users\tonad\Downloads\toxygen-master\toxygen\profile.py", line 1463, in tox_factory
    return Tox(tox_options)
  File "C:\Users\tonad\Downloads\toxygen-master\toxygen\tox.py", line 99, in __init__
    self.AV = ToxAV(self._tox_pointer)
  File "C:\Users\tonad\Downloads\toxygen-master\toxygen\toxav.py", line 32, in __init__
    self._toxav_pointer = self.libtoxav.toxav_new(tox_pointer, byref(toxav_err_new))
OSError: exception: access violation reading 0x000000007998B3C0

**Comment by ingvar1995** [comment]
Hello! Please provide following information:
1. Branch name
2. Where did you download all libs?
3. Does precompiled version work for you?

**Comment by arnking** [comment]
thanks for the reply
1.I try 0.4.2  ; 0.4.1
2.https://codeload.github.com/toxygen-project/toxygen/zip/v0.4.2
   https://codeload.github.com/toxygen-project/toxygen/zip/v0.4.1
3.precompiled version can run in my system,but I want it connet to other software to automatic send some message , so I tried to modify this software.

**Comment by ingvar1995** [comment]
Sounds like one mysterious bug I saw a long time ago. Did you try 32-bit python or other 64-bit python versions? Also did you look into plugins, mb you can achieve your goal using plugins only. Even if it's not possible and updating/reinstalling python doesn't fix the issue you can try to compile build manually and check if it works.

**Comment by EchoBlam** [comment]
Is it solved? I'm also having this issue, I tried python 3.5, 3.6, 3.7, 3.8, 3.11 and it didn't work。The version of python used, and the version that depends
